<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="http://erp.xiangjiamuye.com:8999/ormrpc/services/WSDSStockMoveWSFacade" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="http://erp.xiangjiamuye.com:8999/ormrpc/services/WSDSStockMoveWSFacade" xmlns:intf="http://erp.xiangjiamuye.com:8999/ormrpc/services/WSDSStockMoveWSFacade" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns1="urn:client.dsstockmovewsfacade" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<!--WSDL created by Apache Axis version: 1.4.1-SNAPSHOT
Built on Jun 15, 2017 (10:55:06 UTC)-->
 <wsdl:types>
  <schema targetNamespace="urn:client.dsstockmovewsfacade" xmlns="http://www.w3.org/2001/XMLSchema">
   <import namespace="http://schemas.xmlsoap.org/soap/encoding/"/>
   <complexType name="WSInvokeException">
    <sequence/>
   </complexType>
  </schema>
 </wsdl:types>

   <wsdl:message name="crtStockTransferBillRequest">

      <wsdl:part name="data" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="crtStockTransferBillResponse">

      <wsdl:part name="crtStockTransferBillReturn" type="xsd:string">

      </wsdl:part>

   </wsdl:message>

   <wsdl:message name="WSInvokeException">

      <wsdl:part name="fault" type="tns1:WSInvokeException">

      </wsdl:part>

   </wsdl:message>

   <wsdl:portType name="WSDSStockMoveWSFacadeSrvProxy">

      <wsdl:operation name="crtStockTransferBill" parameterOrder="data">

         <wsdl:input message="impl:crtStockTransferBillRequest" name="crtStockTransferBillRequest">

       </wsdl:input>

         <wsdl:output message="impl:crtStockTransferBillResponse" name="crtStockTransferBillResponse">

       </wsdl:output>

         <wsdl:fault message="impl:WSInvokeException" name="WSInvokeException">

       </wsdl:fault>

      </wsdl:operation>

   </wsdl:portType>

   <wsdl:binding name="WSDSStockMoveWSFacadeSoapBinding" type="impl:WSDSStockMoveWSFacadeSrvProxy">

      <wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>

      <wsdl:operation name="crtStockTransferBill">

         <wsdlsoap:operation soapAction=""/>

         <wsdl:input name="crtStockTransferBillRequest">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://webservice.stockmove.dianshang.webservice.eas.kingdee.com" use="encoded"/>

         </wsdl:input>

         <wsdl:output name="crtStockTransferBillResponse">

            <wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="http://erp.xiangjiamuye.com:8999/ormrpc/services/WSDSStockMoveWSFacade" use="encoded"/>

         </wsdl:output>

         <wsdl:fault name="WSInvokeException">

            <wsdlsoap:fault encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" name="WSInvokeException" namespace="http://erp.xiangjiamuye.com:8999/ormrpc/services/WSDSStockMoveWSFacade" use="encoded"/>

         </wsdl:fault>

      </wsdl:operation>

   </wsdl:binding>

   <wsdl:service name="WSDSStockMoveWSFacadeSrvProxyService">

      <wsdl:port binding="impl:WSDSStockMoveWSFacadeSoapBinding" name="WSDSStockMoveWSFacade">

         <wsdlsoap:address location="http://erp.xiangjiamuye.com:8999/ormrpc/services/WSDSStockMoveWSFacade"/>

      </wsdl:port>

   </wsdl:service>

</wsdl:definitions>
